spring.application.name=PetHealthCloudBackend2

spring.datasource.url=jdbc:mysql://localhost:3306/pethealthcloud
spring.datasource.username=root
spring.datasource.password=860306

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
